.MODEL SMALL
.STACK 100H

;SCRIVI UN PROGRAMMA CHE DATI IN INPUT DUE NUMERI NE FACCIA LA SOMMA

.DATA
	A DB ?
	B DB ?
	RICH DB "Inserisci un numero: ", '$' ;QUESTA STRINGA MI SERVE PER POTERLA MOSTRARE IN INPUT
	INVIO DB 13,10, '$' ;ENDL
	SOMMA DW ?
	FINE DB "Somma: ", '$' ;FINE DEL PROGRAMMA, OVVERO MOSTRA LA SOMMA
.CODE
.STARTUP
	MOV AH, 09H ;OUTPUT
	MOV DX, OFFSET RICH
	INT 21H
	
	MOV AH, 01H ;INPUT
	INT 21H
	MOV A, AL
	
	MOV AH, 09H
	MOV DX, OFFSET INVIO
	INT 21H
	
	MOV AH, 09H ;OUTPUT
	MOV DX, OFFSET RICH
	INT 21H
	
	MOV AH, 01H ;INPUT
	INT 21H
	MOV B, AL
	
	MOV AH, 09H
	MOV DX, OFFSET INVIO
	INT 21H
	
	MOV AL, A
	ADD AL, B
	MOV SOMMA, AX
	
	MOV AH, 09H ;OUTPUT
	MOV DX, OFFSET FINE
	INT 21H
	
	SUB SOMMA, 30H
	
	MOV AH, 09H ;OUTPUT
	MOV DX, OFFSET SOMMA
	INT 21H
	
	MOV AH, 09H
	MOV DX, OFFSET INVIO
	INT 21H
	
	MOV AH, 4CH
	INT 21H
END